In [34]:
from core.nn_model import build_model
from core.dataset import generate_dataset, generate_test_dataset

import matplotlib.pyplot as plt
from PIL import ImageFile

import tensorflow as tf
from tensorflow import keras
import os
import matplotlib.pyplot as plt
from pathlib import Path
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

In [35]:
"""
variables
"""
# not changable variables
# fix bug
ImageFile.LOAD_TRUNCATED_IMAGES = True
main_dir_path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath('test_ntb.ipynb'))))
# path to train folder
train_folder_path = os.path.join(main_dir_path, r"data\\Dataset_ready\\")
# input image size
im_size = (224, 224)

# labels for clases - dataset
CLASS_NAMES = [
        'Num: 0', 'Num: 1', 'Num: 2', 'Num: 3',
        'Num: 4', 'Num: 5', 'Num: 6',
        'Num: 7', 'Num: 8', 'Num: 9']



In [31]:
def load_w(model, PATH_TO_WEIGHS):
    # The model weights (that are considered the best)
    # are loaded into the model.
    latest = tf.train.latest_checkpoint(PATH_TO_WEIGHS)
    model.load_weights(latest)

    return model


In [40]:
"""
variables
"""
NUM_CLASSES = 10
IMG_SIZE = (224, 224)
PATH_TO_WEIGHS = os.path.join(main_dir_path, r'results\\training_checkpoints\\colab_weigts_fine_tuning')

print(PATH_TO_WEIGHS)
# main dataset path
PATH_TO_DATASET = os.path.join(main_dir_path, r'data\\Dataset_ready\\')
PATH_TO_IMG = os.path.join(main_dir_path, r'data\\test\\camera\\')

test_folder_path = os.path.join(
    os.path.dirname(main_dir_path),
    r'breach_elevator\Accelero_processing\Data_for_fusion\MERENI_18_2_2021_display_photo')

"""
MAIN CODE
"""
model_old = build_model(NUM_CLASSES)
model = load_w(model_old, PATH_TO_WEIGHS)
# camera_prediction(model, IMG_SIZE)
# predict_img_folder(model, PATH_TO_IMG, image_size=IMG_SIZE)

c:\Users\marti\Disk Google\DIPLOMKA\KODING\TF2_OD_BRE\results\\training_checkpoints\\colab_weigts_fine_tuning


In [41]:
"""
    evaluate dataset and compute confusion matrix
"""

y_pred = []
test_ds = generate_test_dataset(test_folder_path, image_size=IMG_SIZE)
y_true = test_ds.classes  # numpy array of all labels
print(y_true)

# go trough all folders in the path
for fo_number, folder in enumerate(sorted(os.listdir(test_folder_path))):
    print("new folder:", folder)
    for fi_number, filename in enumerate(os.listdir(test_folder_path+'/'+folder)):
        img_path = test_folder_path+'\\'+str(folder)+'\\'+str(filename)
        img = keras.preprocessing.image.load_img(
            img_path,
            target_size=IMG_SIZE,
            color_mode="rgb",
            grayscale=False
        )

        img_array = keras.preprocessing.image.img_to_array(img)
        tf_img_array = tf.expand_dims(img_array, 0)  # Create batch axis

        predictions = model.predict(tf_img_array)
        Y_pred = np.around(predictions)  # round prediction
        Y_pred = Y_pred.argmax(axis=1)[0]
        y_pred.append(Y_pred)
    print(y_pred)

 6]
new folder: 1
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 4, 4, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 4, 4, 1, 1, 1, 1, 1, 4, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 7, 1, 1, 1, 1, 1, 0, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 4, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 4, 1, 4, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
new folder: 2
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 4, 4, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 4, 4, 1, 1, 1, 1, 1, 4, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 

In [42]:
print('Confusion Matrix')
print(confusion_matrix(y_true, y_pred))

Confusion Matrix
[[  6 222   0   0  16   0   0   1]
 [  0   0 312   0   0  40   0   0]
 [  0   0   0 176   0   0   0   0]
 [  0   0   0   0 106   0   0   0]
 [  0   0   0   0   0 136   0   0]
 [  0   0   0   0   0   1 333   0]
 [  8   0   2   0   3   0   2 131]
 [  0   0   0   0   0   0   0   0]]
