In [1]:
from core.nn_model import build_model
from core.dataset import generate_dataset, generate_test_dataset

import matplotlib.pyplot as plt
from PIL import ImageFile

import tensorflow as tf
from tensorflow import keras
import os
import matplotlib.pyplot as plt
from pathlib import Path
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

In [2]:
"""
variables
"""
# not changable variables
# fix bug
ImageFile.LOAD_TRUNCATED_IMAGES = True
# path to TF2_OD_BRE
main_dir_path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath('test_ntb.ipynb'))))

# path to DIPLOMKA
diplomka_path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath('test_ntb.ipynb'))))))
# path to train folder
train_folder_path = os.path.join(main_dir_path, r"data\\Dataset_ready\\")
# input image size
im_size = (224, 224)

# labels for clases - dataset
CLASS_NAMES = [
        'Num: 0', 'Num: 1', 'Num: 2', 'Num: 3',
        'Num: 4', 'Num: 5', 'Num: 6',
        'Num: 7', 'Num: 8', 'Num: 9']



In [3]:
def load_w(model, PATH_TO_WEIGHS):
    # The model weights (that are considered the best)
    # are loaded into the model.
    latest = tf.train.latest_checkpoint(PATH_TO_WEIGHS)
    model.load_weights(latest)

    return model


In [4]:
"""
variables
"""
NUM_CLASSES = 10
IMG_SIZE = (224, 224)
PATH_TO_WEIGHS = os.path.join(main_dir_path, r'results\\training_checkpoints\\colab_weigts_fine_tuning')

print(PATH_TO_WEIGHS)
# main dataset path
PATH_TO_DATASET = os.path.join(main_dir_path, r'data\\Dataset_ready\\')
PATH_TO_IMG = os.path.join(main_dir_path, r'data\\test\\camera\\')

test_folder_path = os.path.join(
    diplomka_path,
    r'DATA\DISPLAY_IMAGES\images_classes_from_camera\A1')

"""
MAIN CODE
"""
model_old = build_model(NUM_CLASSES)
model = load_w(model_old, PATH_TO_WEIGHS)
# camera_prediction(model, IMG_SIZE)
# predict_img_folder(model, PATH_TO_IMG, image_size=IMG_SIZE)

c:\Users\marti\Disk Google\DIPLOMKA\KODING\TF2_OD_BRE\results\\training_checkpoints\\colab_weigts_fine_tuning


In [12]:
"""
    evaluate dataset and compute confusion matrix
"""
test_folder_path = "C:\\Users\\marti\\OneDrive\\Plocha\\DP_OBRAZKY_DISPLAY\\display_classes_0-9_preprocessed"


y_pred = []
test_ds = generate_test_dataset(test_folder_path, image_size=IMG_SIZE)
y_true = test_ds.classes  # numpy array of all labels
print(y_true)

# go trough all folders in the path
for fo_number, folder in enumerate(sorted(os.listdir(test_folder_path))):
    print("new folder:", folder)
    for fi_number, filename in enumerate(os.listdir(test_folder_path+'/'+folder)):
        img_path = test_folder_path+'\\'+str(folder)+'\\'+str(filename)
        img = keras.preprocessing.image.load_img(
            img_path,
            target_size=IMG_SIZE,
            color_mode="rgb",
            grayscale=False
        )

        img_array = keras.preprocessing.image.img_to_array(img)
        tf_img_array = tf.expand_dims(img_array, 0)  # Create batch axis

        predictions = model.predict(tf_img_array)
        Y_pred = np.around(predictions)  # round prediction
        Y_pred = Y_pred.argmax(axis=1)[0]
        y_pred.append(Y_pred)

print('Confusion Matrix')
print(confusion_matrix(y_true, y_pred))

Found 15034 images belonging to 10 classes.
[0 0 0 ... 9 9 9]
new folder: 01_0
new folder: 02_1
new folder: 03_2
new folder: 04_3
new folder: 05_4
new folder: 06_5
new folder: 07_6
new folder: 08_7
new folder: 09_8
new folder: 10_9
Confusion Matrix
[[1365   28    0    2    3    0    3    0    3    0]
 [  86 2731    1   71   59    0    5   50    0    0]
 [   7    3 2142  123    8   56    0    0    0    0]
 [  17    0    1 2249    6   13    0    6    0    0]
 [  20   16    0    6 1455   17    3    2    0    0]
 [   8    3  109   54   18 1556    3    0    0    0]
 [  11    4    1   47    1   33  885    1    0    0]
 [  27   44   23   40   58   12    0  550    0    0]
 [ 143    0    0    6    0   25   19    0  376   10]
 [  43    0    0    2    2  113    4    0   12  234]]


In [5]:
"""
    evaluate dataset and compute confusion matrix
"""
test_folder_path = os.path.join(
    diplomka_path,
    r'DATA\DISPLAY_IMAGES\images_classes_from_camera\A1')


y_pred = []
test_ds = generate_test_dataset(test_folder_path, image_size=IMG_SIZE)
y_true = test_ds.classes  # numpy array of all labels
print(y_true)

# go trough all folders in the path
for fo_number, folder in enumerate(sorted(os.listdir(test_folder_path))):
    print("new folder:", folder)
    for fi_number, filename in enumerate(os.listdir(test_folder_path+'/'+folder)):
        img_path = test_folder_path+'\\'+str(folder)+'\\'+str(filename)
        img = keras.preprocessing.image.load_img(
            img_path,
            target_size=IMG_SIZE,
            color_mode="rgb",
            grayscale=False
        )

        img_array = keras.preprocessing.image.img_to_array(img)
        tf_img_array = tf.expand_dims(img_array, 0)  # Create batch axis

        predictions = model.predict(tf_img_array)
        Y_pred = np.around(predictions)  # round prediction
        Y_pred = Y_pred.argmax(axis=1)[0]
        y_pred.append(Y_pred)

Found 787 images belonging to 10 classes.
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7

In [6]:
print('Confusion Matrix')
print(confusion_matrix(y_true, y_pred))

Confusion Matrix
[[  0   0   0   0   0   0   0   0   0   0]
 [ 15  18   2   0  23   0   0   0   0   0]
 [  1   0  71   0   0   1   0   0   0   0]
 [ 13   0   0  31   0   0   1   3   0   0]
 [  1   0   0   0  54   1   0   0   0   0]
 [  2   0   0   0   0 117   0   0   0   0]
 [  0   0   0   0   1   2  86   0   0   0]
 [ 20  69   2   1  26   0   0  21   0   0]
 [  0   0   0   0   0   0  50   0  46   0]
 [ 16   0   0   2   8  67  16   0   0   0]]


In [7]:
"""
    evaluate dataset and compute confusion matrix
"""
test_folder_path = os.path.join(
    diplomka_path,
    r'DATA\DISPLAY_IMAGES\images_classes_from_camera\A3_01')


y_pred = []
test_ds = generate_test_dataset(test_folder_path, image_size=IMG_SIZE)
y_true = test_ds.classes  # numpy array of all labels
print(y_true)

# go trough all folders in the path
for fo_number, folder in enumerate(sorted(os.listdir(test_folder_path))):
    print("new folder:", folder)
    for fi_number, filename in enumerate(os.listdir(test_folder_path+'/'+folder)):
        img_path = test_folder_path+'\\'+str(folder)+'\\'+str(filename)
        img = keras.preprocessing.image.load_img(
            img_path,
            target_size=IMG_SIZE,
            color_mode="rgb",
            grayscale=False
        )

        img_array = keras.preprocessing.image.img_to_array(img)
        tf_img_array = tf.expand_dims(img_array, 0)  # Create batch axis

        predictions = model.predict(tf_img_array)
        Y_pred = np.around(predictions)  # round prediction
        Y_pred = Y_pred.argmax(axis=1)[0]
        y_pred.append(Y_pred)

print('Confusion Matrix')
print(confusion_matrix(y_true, y_pred))

Found 3409 images belonging to 10 classes.
[1 1 1 ... 7 7 9]
new folder: 0
new folder: 1
new folder: 2
new folder: 3
new folder: 4
new folder: 5
new folder: 6
new folder: 7
new folder: 8
new folder: 9
Confusion Matrix
[[  0   0   0   0   0   0   0   0   0]
 [ 20 464   0   0  30   0   1   4   0]
 [  0   0 718   0   0 159   0   0   0]
 [  0   0   0 321   0   0   0   0   0]
 [  0   0   0   0 373   4   0   0   0]
 [  0   0   0   0   0 440   0   0   0]
 [  0   0   0   0   0   3 559   0   0]
 [ 41  41   6   2   6   0   0 216   0]
 [  0   0   0   0   0   0   1   0   0]]


In [8]:
"""
    evaluate dataset and compute confusion matrix
"""
test_folder_path = os.path.join(
    diplomka_path,
    r'DATA\DISPLAY_IMAGES\images_classes_from_camera\A4')


y_pred = []
test_ds = generate_test_dataset(test_folder_path, image_size=IMG_SIZE)
y_true = test_ds.classes  # numpy array of all labels
print(y_true)

# go trough all folders in the path
for fo_number, folder in enumerate(sorted(os.listdir(test_folder_path))):
    print("new folder:", folder)
    for fi_number, filename in enumerate(os.listdir(test_folder_path+'/'+folder)):
        img_path = test_folder_path+'\\'+str(folder)+'\\'+str(filename)
        img = keras.preprocessing.image.load_img(
            img_path,
            target_size=IMG_SIZE,
            color_mode="rgb",
            grayscale=False
        )

        img_array = keras.preprocessing.image.img_to_array(img)
        tf_img_array = tf.expand_dims(img_array, 0)  # Create batch axis

        predictions = model.predict(tf_img_array)
        Y_pred = np.around(predictions)  # round prediction
        Y_pred = Y_pred.argmax(axis=1)[0]
        y_pred.append(Y_pred)

print('Confusion Matrix')
print(confusion_matrix(y_true, y_pred))

Found 1776 images belonging to 10 classes.
[1 1 1 ... 9 9 9]
new folder: 0
new folder: 1
new folder: 2
new folder: 3
new folder: 4
new folder: 5
new folder: 6
new folder: 7
new folder: 8
new folder: 9
Confusion Matrix
[[  0   0   0   0   0   0   0   0   0   0]
 [  0  83   0   0  11   0   0   0   0   0]
 [  0   1 536   1   1  32   1   0   0   0]
 [  0   0   0 197   0   1   0   0   0   0]
 [  0   0   0   0 186   0   0   0   0   0]
 [  0   0   0   0   0 227   0   0   0   0]
 [  0   0   0   0   0  40 179   0   0   0]
 [  3   6   2   0   0   0   0 263   0   0]
 [  0   0   0   0   0   0   0   0   1   0]
 [  0   0   0   0   0   5   0   0   0   0]]


In [10]:
"""
    evaluate dataset and compute confusion matrix
"""
test_folder_path = os.path.join(
    diplomka_path,
    r'DATA\DISPLAY_IMAGES\images_classes_from_camera\Pricni')


y_pred = []
test_ds = generate_test_dataset(test_folder_path, image_size=IMG_SIZE)
y_true = test_ds.classes  # numpy array of all labels
print(y_true)

# go trough all folders in the path
for fo_number, folder in enumerate(sorted(os.listdir(test_folder_path))):
    print("new folder:", folder)
    for fi_number, filename in enumerate(os.listdir(test_folder_path+'/'+folder)):
        img_path = test_folder_path+'\\'+str(folder)+'\\'+str(filename)
        img = keras.preprocessing.image.load_img(
            img_path,
            target_size=IMG_SIZE,
            color_mode="rgb",
            grayscale=False
        )

        img_array = keras.preprocessing.image.img_to_array(img)
        tf_img_array = tf.expand_dims(img_array, 0)  # Create batch axis

        predictions = model.predict(tf_img_array)
        Y_pred = np.around(predictions)  # round prediction
        Y_pred = Y_pred.argmax(axis=1)[0]
        y_pred.append(Y_pred)

print('Confusion Matrix')
print(confusion_matrix(y_true, y_pred))

Found 1366 images belonging to 10 classes.
[0 0 0 ... 7 8 9]
new folder: 0
new folder: 1
new folder: 2
new folder: 3
new folder: 4
new folder: 5
new folder: 6
new folder: 7
new folder: 8
new folder: 9
Confusion Matrix
[[161  11   1  45   1   0   0   0   0   0]
 [143  13   0  48  54   0   0   0   0   0]
 [ 31   0  65 111   0   6   0   0   0   0]
 [  1   0   0 409   0   0   0   0   0   0]
 [ 11   0   1  92   4   0   0   0   0   0]
 [ 16   0  14  77   0  47   0   0   0   0]
 [  0   0   0   1   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   0   0   0]]


In [9]:
"""
    evaluate dataset and compute confusion matrix
"""
test_folder_path = os.path.join(
    diplomka_path,
    r'DATA\DISPLAY_IMAGES\images_classes_from_mobile\10_classes_0_9')


y_pred = []
test_ds = generate_test_dataset(test_folder_path, image_size=IMG_SIZE)
y_true = test_ds.classes  # numpy array of all labels
print(y_true)

# go trough all folders in the path
for fo_number, folder in enumerate(sorted(os.listdir(test_folder_path))):
    print("new folder:", folder)
    for fi_number, filename in enumerate(os.listdir(test_folder_path+'/'+folder)):
        img_path = test_folder_path+'\\'+str(folder)+'\\'+str(filename)
        img = keras.preprocessing.image.load_img(
            img_path,
            target_size=IMG_SIZE,
            color_mode="rgb",
            grayscale=False
        )

        img_array = keras.preprocessing.image.img_to_array(img)
        tf_img_array = tf.expand_dims(img_array, 0)  # Create batch axis

        predictions = model.predict(tf_img_array)
        Y_pred = np.around(predictions)  # round prediction
        Y_pred = Y_pred.argmax(axis=1)[0]
        y_pred.append(Y_pred)

print('Confusion Matrix')
print(confusion_matrix(y_true, y_pred))

Found 12899 images belonging to 10 classes.
[0 0 0 ... 9 9 9]
new folder: 0
new folder: 1
new folder: 2
new folder: 3
new folder: 4
new folder: 5
new folder: 6
new folder: 7
new folder: 8
new folder: 9
Confusion Matrix
[[1151   26    3    5    0    0    0    0    1    0]
 [  34 2608    5  136   24    1    1   71    0    0]
 [  19    5 1991   88    1   25    0    1    0    0]
 [   5    1    2 2099    0   49    0    3    0    0]
 [  64   30   22    8 1145    4    0    1    4    4]
 [  24    0  150   43    5 1403    0    0    0    0]
 [   0    0    0    0    0    1  705    0    5    0]
 [  11    0    5   11   35    6    0  392    1    0]
 [   9    0    0    1    0    0    3    0  198   13]
 [   3    0    0    1    0   19    0    0    0  218]]


In [11]:
"""
    evaluate dataset and compute confusion matrix
"""
test_folder_path = os.path.join(
    diplomka_path,
    r'DATA\DISPLAY_IMAGES\images_classes_from_camera\All_preprocessed')


y_pred = []
test_ds = generate_test_dataset(test_folder_path, image_size=IMG_SIZE)
y_true = test_ds.classes  # numpy array of all labels
print(y_true)

# go trough all folders in the path
for fo_number, folder in enumerate(sorted(os.listdir(test_folder_path))):
    print("new folder:", folder)
    for fi_number, filename in enumerate(os.listdir(test_folder_path+'/'+folder)):
        img_path = test_folder_path+'\\'+str(folder)+'\\'+str(filename)
        img = keras.preprocessing.image.load_img(
            img_path,
            target_size=IMG_SIZE,
            color_mode="rgb",
            grayscale=False
        )

        img_array = keras.preprocessing.image.img_to_array(img)
        tf_img_array = tf.expand_dims(img_array, 0)  # Create batch axis

        predictions = model.predict(tf_img_array)
        Y_pred = np.around(predictions)  # round prediction
        Y_pred = Y_pred.argmax(axis=1)[0]
        y_pred.append(Y_pred)

print('Confusion Matrix')
print(confusion_matrix(y_true, y_pred))

Found 6191 images belonging to 10 classes.
[0 0 0 ... 9 9 9]
new folder: 0
new folder: 1
new folder: 2
new folder: 3
new folder: 4
new folder: 5
new folder: 6
new folder: 7
new folder: 8
new folder: 9
Confusion Matrix
[[ 195    0    0   23    1    0    0    0    0    0]
 [  25  608    2    1   23    0    1   11    0    0]
 [   3    5 1387    0    2  123    1    1    0    0]
 [   4    0    0  561    0    2    0    0    0    0]
 [   2    0    0    0  613    4    0    0    0    0]
 [   7    0    1    0    2  776    0    0    0    0]
 [   3    0    0    1    0   32  834    0    0    0]
 [  56   60    1    4   20    0    0  584    0    0]
 [   1    0    0    0    0    0   10    0   86    0]
 [   9    0    0    0    1   24    9    0   37   35]]
